# Generated by Django 3.2 on 2022-03-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '글 작성하기'},
        ),
    ]
